name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        if: ${{ !env.ACT }}
        with:
          fetch-depth: 0
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        if: ${{ !env.ACT }}
        with:
          node-version: 20
          
      - name: Build
        if: ${{ !env.ACT }}
        run: |
          npm install
          npm run build
        
      - name: Commit and push if changed
        if: ${{ !env.ACT }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if ! git diff --exit-code --quiet; then
            git add .
            git commit -m "Update dist"
            git push origin main
          fi
          
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        if: ${{ !env.ACT }}
        with:
          token: ${{ github.token }}
          branch: main
          
      - name: Create Release
        if: ${{ !env.ACT }}
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag:  ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
